version: "2"

services:
  web:
    build: ./baseA
    ports:
      - "8001:8001"
    links:
    - db

  web2:
    build: ./baseB
    ports:
      - "8002:8002"
    links:
    - db

  web3:
    build: ./baseC
    ports:
      - "8003:8003"
    links:
    - db

  web4:
    build: ./authentication
    ports:
      - "8000:8000"
    
    links:
    - db2
  
  db2:
    image: postgres:latest
    expose:
      - "5432"
    ports:
     - "5432:5432"

  db:
    image: mongo:3.0.2
    expose:
      - "27017"
    ports:
      - "27017:27017"